#!/bin/bash
# ─────────────────────────────────────────────────────────────
#  Proxmox Atlas — One-Line Installer
#  Usage:  curl -sSL https://raw.githubusercontent.com/Losstarot85/proxmox-atlas/main/install.sh | bash
#  Update: cd /opt/proxmox-atlas && ./install.sh --update
# ─────────────────────────────────────────────────────────────
set -e

REPO="Losstarot85/proxmox-atlas"
INSTALL_DIR="/opt/proxmox-atlas"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

banner() {
    echo -e "${CYAN}"
    echo "  ╔═══════════════════════════════════════════════════╗"
    echo "  ║           Proxmox Atlas Installer                 ║"
    echo "  ║       Multi-Cluster Monitoring Dashboard          ║"
    echo "  ╚═══════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

log()   { echo -e "  ${GREEN}✓${NC} $1"; }
warn()  { echo -e "  ${YELLOW}⚠${NC} $1"; }
error() { echo -e "  ${RED}✗${NC} $1"; exit 1; }
info()  { echo -e "  ${BLUE}→${NC} $1"; }

# ─── Prerequisites ───
check_prerequisites() {
    info "Checking prerequisites..."

    if ! command -v docker &> /dev/null; then
        error "Docker is not installed. Please install Docker first: https://docs.docker.com/engine/install/"
    fi
    log "Docker found: $(docker --version | head -1)"

    if ! docker compose version &> /dev/null; then
        error "Docker Compose V2 is not available. Please update Docker or install the compose plugin."
    fi
    log "Docker Compose found: $(docker compose version --short)"

    if ! command -v git &> /dev/null; then
        error "Git is not installed. Please install git first."
    fi
    log "Git found: $(git --version)"

    if ! command -v openssl &> /dev/null; then
        warn "OpenSSL not found on host. SSL certs will be generated inside the container."
    fi
}

# ─── Clone or Update ───
clone_or_update() {
    if [ -d "$INSTALL_DIR/.git" ]; then
        info "Existing installation found. Pulling latest changes..."
        cd "$INSTALL_DIR"
        git pull --ff-only || { warn "Git pull failed. Continuing with current version."; }
        log "Repository updated."
    else
        info "Cloning Proxmox Atlas to $INSTALL_DIR..."
        git clone "https://github.com/$REPO.git" "$INSTALL_DIR"
        cd "$INSTALL_DIR"
        log "Repository cloned."
    fi
}

# ─── Generate Self-Signed SSL Certificate ───
generate_ssl_cert() {
    CERT_DIR="$INSTALL_DIR/certs"
    CERT_FILE="$CERT_DIR/atlas.crt"
    KEY_FILE="$CERT_DIR/atlas.key"

    if [ -f "$CERT_FILE" ] && [ -f "$KEY_FILE" ]; then
        log "SSL certificates already exist, skipping generation."
        return
    fi

    info "Generating self-signed SSL certificate..."
    mkdir -p "$CERT_DIR"

    if command -v openssl &> /dev/null; then
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
            -keyout "$KEY_FILE" \
            -out "$CERT_FILE" \
            -subj "/CN=proxmox-atlas/O=Proxmox Atlas" \
            -addext "subjectAltName=DNS:localhost,IP:127.0.0.1" 2>/dev/null

        chmod 644 "$CERT_FILE"
        chmod 600 "$KEY_FILE"
        log "Self-signed SSL certificate generated."
    else
        warn "OpenSSL not available on host. Certificate will be generated by the Nginx container on first boot."
    fi
}

# ─── Build & Start ───
build_and_start() {
    info "Building and starting Proxmox Atlas (this may take a few minutes on first run)..."
    cd "$INSTALL_DIR"
    docker compose up -d --build
    log "All containers started successfully."
}

# ─── Main ───
banner
check_prerequisites
clone_or_update
generate_ssl_cert
build_and_start

# Detect primary IP
PRIMARY_IP=$(hostname -I 2>/dev/null | awk '{print $1}')
[ -z "$PRIMARY_IP" ] && PRIMARY_IP="localhost"

echo ""
echo -e "  ${GREEN}${BOLD}✅ Proxmox Atlas is now running!${NC}"
echo ""
echo -e "  ${BOLD}Dashboard:${NC}    ${BLUE}https://${PRIMARY_IP}${NC}"
echo -e "  ${BOLD}Credentials:${NC}  ${YELLOW}admin / admin${NC}"
echo -e "  ${BOLD}Note:${NC}         You will be prompted to change the password on first login."
echo ""
echo -e "  ${BOLD}Custom SSL:${NC}"
echo -e "    cp your-cert.pem ${INSTALL_DIR}/certs/atlas.crt"
echo -e "    cp your-key.pem  ${INSTALL_DIR}/certs/atlas.key"
echo -e "    cd ${INSTALL_DIR} && docker compose restart nginx"
echo ""
echo -e "  ${BOLD}Manage:${NC}"
echo -e "    cd ${INSTALL_DIR}"
echo -e "    docker compose logs -f        ${CYAN}# View logs${NC}"
echo -e "    docker compose restart         ${CYAN}# Restart all${NC}"
echo -e "    docker compose down            ${CYAN}# Stop all${NC}"
echo -e "    ./install.sh --update          ${CYAN}# Update to latest${NC}"
echo ""
